version: '3'
services:
    redis:
      image: redis:latest
      container_name: redis-dating
      ports:
        - "6379:6379"
      privileged: true
      sysctls:
        net.core.somaxconn: "511"

    worker:
        build:
            context: .
            dockerfile: dockerfile
        command: /bin/bash -c "celery -A myproject worker --loglevel=info"
        volumes:
            - .:/code
        links:
            - redis
        depends_on:
            - redis
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - worker
            - redis


