# Generated by Django 2.2.6 on 2019-11-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
