# Generated by Django 2.2.6 on 2019-11-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
