# Generated by Django 2.2.6 on 2019-11-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_boardactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardActions',
        ),
    ]
