# Generated by Django 2.2.6 on 2019-11-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_galleryimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImages',
        ),
    ]
